Fedora fix tests
tpm2-software/tpm2-openssl pull request #69
Opened 2023-05-07 22:35 UTC by afreof

The first commit is probably ready

Not sure what we should do with the second commit: It allows to run all tests in a Fedora container (podman rootless). swtpm and ibm TPM simulators are supported.

2023-05-08 13:37 UTC, hoinmic approved these changes

2023-05-09 13:01 UTC, gotthardp requested changes
Would it be possible to have the `Containerfiles` directory under `test`, to not complicate the roo directory of the entire project?

2023-05-15 16:30 UTC, afreof commented
- Moved Containerfiles to the test folder
- Moved documentation to the suggested section

2023-05-15 18:19 UTC, merged

2023-05-15 18:20 UTC, gotthardp commented
Thank you!